version: '3.4'

services:
  tvmnproject:
    image: tvmnproject
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5500:5500
