version: '3.4'

services:
  tvmn-project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tvmn-project
    command: yarn dev
    env_file:
      - .env
    ports:
      - '5500:5500'
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
